name: Build and release yad

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install required packages
      run: sudo apt install \
              autoconf \
              automake \
              intltool \
              libgtk-3-dev \
              libglib2.0-dev

    - name: Retrieve Yad source code
      run: git clone https://github.com/v1cont/yad/tree/v13.0 yad-dialog-code
    
    - name: Retrieve linux deploy
      run: |
        wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
        chmod +x ./linuxdeploy-x86_64.AppImage
        ./linuxdeploy-x86_64.AppImage --appimage-extract

    - name: Build Yad
      working-directory: yad-dialog-code
      run: |
          autoreconf -ivf
          intltoolize
          ./configure prefix=$(pwd)/AppDir --enable-standalone
          make
          make install

    - name: Prepare .desktop file
      working-directory: yad-dialog-code
      run: cat << EOF > ./yad.desktop 
          [Desktop Entry]
          Encoding=UTF-8
          Name=Yad
          Categories=GTK;Development;
          Exec=yad
          Icon=yad
          Terminal=true
          Type=Application
          StartupNotify=true
          EOF

    - name: Create Appimage
      working-directory: yad-dialog-code
      run: ../squashfs-root/AppRun \
          --appdir ./AppDir \
          -i ./data/icons/128x128/yad.png \
          --executable ./AppDir/bin/yad \
          -d ./yad.desktop \
          --output appimage

    - name: Move Appimage
      run: mv ./yad-dialog-code/*.AppImage Yad-13.0-x86_64.AppImage

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: Yad-13.0-x86_64.AppImage
        body: "[`yad`](https://github.com/v1cont/yad) 13.0 appimage built on ubuntu with github actions"
